collection/urls.py
from django.urls import path
from . import views

app_name = 'collection'

urlpatterns = [
	path('', views.collections_render, name='collections'),
	path('get-images', views.ajax_get_images, name='ajax_get_images'),
	path('<str:slug>', views.category_render, name='category'),
	
]

polyshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from register import views as v

handler404 = "store.views.handle_404"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name='register'),
    path('login/', v.handlelogin, name='login'),
    path('logout/', v.handlelogout, name='logout'),
    path('', include('store.urls')),
    path('collections/', include('collection.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('<str:slug>', views.product_render, name='product'),
	path('cart/', views.cart, name='cart'),
	path('checkout/', views.checkout, name='checkout'),
	path('add-review/', views.add_review, name='add_review'),
	path('upload-form-data/', views.upload_form_data, name='upload_form_data'),
	path('variant-price/', views.variant_price, name='variant_price'),
	path('update-quantity/', views.update_quantity, name='update_quantity'),
	path('remove-order-item/', views.remove_order_item, name='remove_order_item'),
	path('add-product/', views.add_product, name='add_product'),
	path('track_order/', views.track_order, name='track_order'),
	path('about/', views.about_us, name='about'),
	path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
	path('shipping-policy/', views.shipping_policy, name='shipping_policy'),
	path('refund-policy/', views.refund_policy, name='refund_policy'),
	path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
	path('contact_us/', views.contact_us, name='contact_us'),
	path('subscribe/', views.subscribe, name='subscribe'),
	path('coupon_apply/', views.coupon_apply, name='coupon'),
	path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import os
from decimal import Decimal

# Create your models here.

class Customer(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
	name = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)
	device = models.CharField(max_length=200, null=True)

	# def __str__(self):
	# 	return self.name


####################################

class Category(models.Model):
	name = models.CharField(max_length=255)
	slug = models.SlugField(max_length=255, unique=True, blank=True)

	def __str__(self):
		return self.name

class Attribute(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class AttributeValue(models.Model):
	attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
	value = models.CharField(max_length=100)

	def __str__(self):
		return f'{self.attribute} ({self.value})'

class Product(models.Model):
	name = models.CharField(max_length=255)
	slug = models.SlugField(max_length=255, unique=True)
	category = models.ManyToManyField(Category)
	image = models.ImageField(null=True, blank=True)
	crossed_out_price = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
	price = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
	available = models.BooleanField(default=True,null=True, blank=True)
	description = models.TextField(null=True, blank=True)

	def __str__(self):
		return self.name

	def calc_save(self):
		save_persent = (self.crossed_out_price - self.price) / self.crossed_out_price * 100
		return round(save_persent)

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

	@property
	def first_image_url(self):
		try:
			# Отримати перший об'єкт ProductImage, якщо вони є
			first_image = self.productimage_set.first()
			if first_image:
				return first_image.image.url
			else:
				return ''  # Повернути порожній рядок, якщо зображень немає
		except:
			return ''

class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    attribute = models.ManyToManyField(AttributeValue, blank=True)
    price_modifier = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    crossed_out_price_modified = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    def __str__(self):
        return f'{self.product.name} - {self.attribute.all()} (Modifier: {self.price_modifier})'

    def get_attribute_value(self):
    	return self.attribute.value


class ProductImage(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	image = models.ImageField(null=True, blank=True)

	def __str__(self):
		return f'{self.product.name} - Image'

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url


class Review(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
	name = models.CharField(max_length=255, null=True)
	text = models.TextField()
	rating = models.IntegerField()

	def __str__(self):
		return f'Review for {self.product.name}'

	def get_average_rating(self):
		reviews_for_product = Review.objects.filter(product=self.product)

		total_rating_sum = sum(review.rating for review in reviews_for_product)

		if reviews_for_product:
			average_rating = total_rating_sum / len(reviews_for_product)
		else:
			average_rating = 5

		return average_rating

class ReviewImage(models.Model):
	review = models.ForeignKey(Review, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='images/review_photos/', null=True, blank=True)

	def __str__(self):
		return f'{self.review.product.name} - Image'

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False, null=True, blank=False)
	transaction_id = models.CharField(max_length=200, null=True)

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])

		return float(total) 

class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
	variant_title = models.CharField(max_length=500, null=True, blank=True)
	variant_price = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_total(self):
		if self.variant_price == None:
			total = self.product.price * self.quantity
		else:
			total = self.variant_price * self.quantity
		return total

class Coupon(models.Model):
	code = models.CharField(max_length=50, unique=True)
	valid_from = models.DateTimeField()
	valid_to = models.DateTimeField()
	discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.code

class ShippingAddress(models.Model):
	email = models.EmailField()
	first_name = models.CharField(max_length=200, null=True)
	last_name = models.CharField(max_length=200, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	country = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)
	date_added = models.DateTimeField(auto_now_add=True)

	# def __str__(self):
	# 	return str(self.email) if self.email else "No Email Provided"

class Subscription(models.Model):
	email = models.EmailField()

	def __str__(self):
		return str(self.email)

class ContactUs(models.Model):
	name = models.CharField(max_length=200)
	email = models.EmailField()
	message = models.TextField()

store/forms.py
from django import forms

class CouponApplyForm(forms.Form):
	code = forms.CharField()

store/templates/store/about_us.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}
About Us
{% endblock title %}
{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}">
	<style>
		#navbar-container {
			border-bottom: 1px solid #b5b2c8;
		}
		
		#navbar-right li p,
		#navbar-bottom li a,
		#navbar-login li a,
		#navbar li a {
			color: #000;
		} 
	</style>
{% endblock css %}
{% block content %}
	<section class="section-p1">
		<div class="about-container">
			<h2>ABOUT US</h2>
			<p><strong>Welcome to Sage & Sill!</strong> - We're a small business in Spokane, Washington, and we have big dreams. Our passion for plants and home essentials drives us to provide our customers with products that are guaranteed to delight! We thoroughly check the quality of our goods, working only with the best merchants and suppliers so that you receive only the best quality products.</p>

			<p><strong>Luxury for everyone</strong> - We believe shopping is a right, not a privilege, so we strive to offer the best products at the most affordable prices and ship them to you anywhere in the world.</p>

			<p><strong>Always here to help</strong> - Your experience with us doesn't end when your order arrives. We want to earn your trust, over and over again. We insist on exceptional customer service, which is why our friendly customer care team is here to help 7 days a week.</p>
			
			<p><strong>We're not happy until you're happy</strong> - Our customers' best interest is always our top priority, so we hope you love our products as much as we love making them available to you!</p>
		</div>
	</section>
{% endblock content %}

store/templates/store/add_review.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}
Add Review
{% endblock title %}
{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}">
	<style>
		#navbar-container {
			border-bottom: 1px solid #b5b2c8;
		}
		
		#navbar-right li p,
		#navbar-bottom li a,
		#navbar-login li a,
		#navbar li a {
			color: #000;
		} 
	</style>
	<style>
		/* Style for the form container */
		form {
		  max-width: 400px;
		  margin: 0 auto;
		  padding: 20px;
		  border: 1px solid #ccc;
		  border-radius: 5px;
		  font-family: Arial, sans-serif;
		}
	  
		/* Style for form labels */
		label {
		  display: block;
		  margin-bottom: 5px;
		  font-weight: bold;
		}
	  
		/* Style for form inputs */
		input[type="text"],
		input[type="number"],
		select,
		textarea {
		  width: 100%;
		  padding: 10px;
		  margin-bottom: 10px;
		  border: 1px solid #ccc;
		  border-radius: 5px;
		  box-sizing: border-box;
		  font-family: Arial, sans-serif;
		}
	  
		/* Style for the select dropdown */
		select {
		  height: 40px;
		}
	  
		/* Style for the textarea */
		textarea {
		  resize: vertical; /* Allows vertical resizing of the textarea */
		}
	  
		/* Style for the file input */
		input[type="file"] {
		  margin-top: 5px;
		}
	  
		/* Style for the submit button */
		input[type="submit"] {
		  background-color: #4CAF50;
		  color: #fff;
		  border: none;
		  padding: 10px 20px;
		  border-radius: 5px;
		  cursor: pointer;
		}
	  
		/* Additional styles for the submit button on hover */
		input[type="submit"]:hover {
		  background-color: #45a049;
		}
	  </style>	  
{% endblock css %}
{% block content %}
	<h1>Add Review</h1>
	<form method="POST" action="{% url 'add_review' %}" enctype="multipart/form-data">
	{% csrf_token %}
		<label>Select a product</label><br>
        <select name="selected_product">
            <option value='none'>Select a product...</option>
            {% for product in products %}
            	<option value='{{product.slug}}'>{{product.name}}</option>
            {% endfor %}
        </select><br>

        <label>Name</label><br>
        <input type="text" name="name" placeholder="Enter author's name" required><br>

        <label>Revies's text</label><br>
        <textarea name="text" rows="10" required></textarea><br>
        <!-- <input type="text" name="text" placeholder="Enter text" required><br> -->

        <label>Rating</label><br>
        <input type="number" name="rating" placeholder="Enter number of stars (1-5)" required><br>

        <label>Pictures</label><br>
        <input type="file" name="images" required multiple><br>

        <input type="submit" value="Send"/>
	</form>
{% endblock content %}

store/templates/store/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<title>{% block title %}{% endblock title %}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<script type="text/javascript">

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function setCookie(name, value, days) {
      var expirationDate = new Date();
      expirationDate.setDate(expirationDate.getDate() + days); // Додаємо кількість днів до поточної дати
      var expires = "expires=" + expirationDate.toUTCString();
      document.cookie = name + "=" + value + "; " + expires + "; path=/";
    }


    function uuidv4() {
      return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
      });
    }




    let device = getCookie('device');

    if (device == null || device == undefined){
      device = uuidv4();
      setCookie('device', device, 45); 
    }

    // document.cookie ='device=' + device + ";domain=;path=/"

  </script>
{% block css %}

{% endblock css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>Polyshop Homepage</title>
<style>
  
</style>
</head>
<body>
  <div class="announcement">
    <p><b>30-DAY RETURNS</b> Money Back Guarantee</p>
  </div>
  <section id="header">

    <div id="navbar-container">
      <ul id="navbar">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'collection:collections' %}">Departments</a></li>
        <li><a href="{% url 'about' %}">About us</a></li>
        <li><a href="{% url 'shipping_policy' %}">Shipping</a></li>
        <li><a href="{% url 'refund_policy' %}">Refunds</a></li>
        <li><a href="{% url 'track_order' %}">Track Order</a></li>
      </ul>

      <ul id="navbar-right">
        <li><p><i class='fa fa-pinterest'></i></p></li>
        <li><p>Language</p></li>
      </ul>
    </div>

    <div id="categories">
      <a href="{% url 'home' %}"><img class="logo" src="{% static 'images/logo.png' %}"></a>
      <ul id="navbar-bottom">
          <li><a href="{% url 'collection:category' slug='new-arrivals' %}">New Arrivals</a></li>
          <li><a href="{% url 'collection:category' slug='kitchen' %}">Kitchen</a></li>
          <li><a href="{% url 'collection:category' slug='garden' %}">Garden</a></li>
          <li><a href="{% url 'collection:category' slug='home-decor' %}">Home Decor</a></li>
          <li><a href="{% url 'collection:category' slug='bathroom' %}">Bathroom</a></li>
          <li><a href="{% url 'collection:category' slug='pets' %}">Pets</a></li>
          <li><a href="{% url 'collection:category' slug='car' %}">Car</a></li>
          <li><a href="{% url 'collection:category' slug='bestsellers' %}">Bestsellers</a></li>
          <li><a href="{% url 'collection:category' slug='other' %}">Others</a></li>
          <a href="#" id="close"><i class="fa fa-times"></i></a>
      </ul>

      <ul id="navbar-login">
        {% if user.is_authenticated %}
          <li><a href="/logout/">Logout</a></li>
        {% else %}
          <li><a href="/login/">Login</a></li>
        {% endif %}
      </ul>
    </div>
    <div class="mobile">
      <a href="/cart/"><i class='fa fa-shopping-cart'></i></a>
      <i id="bar" class="fa fa-bars"></i>
    </div>
    {% block header %}

    {% endblock header %}
  </section>
  {% block content %}

  {% endblock content %}
  <footer>
    <div class="col">
      <h4>OUR COMPANY</h4>
      <a href="{% url 'about' %}">About Us</a>
      <a href="{% url 'collection:collections' %}">See all Collections</a>
      <a href="#">Contact Us</a>
    </div>

    <div class="col">
      <h4>MY ORDER</h4>
      <a href="#">Track Order</a>
      <!-- <a href="#">Lost, Damaged</a> -->
      <!-- <a href="#">Return or Exchange</a> -->
      <a href="{% url 'shipping_policy' %}">Shipping Times</a>
      <a href="#">FAQ</a>
    </div>

    <div class="col">
      <h4>POLICIES</h4>
      <a href="{% url 'shipping_policy' %}">Shipping Policy</a>
      <a href="{% url 'refund_policy' %}">Refund Policy</a>
      <a href="{% url 'privacy_policy' %}">Privacy Policy</a>
      <a href="{% url 'terms_of_service' %}">Terms of Service</a>
    </div>

    <div class="col col-over">
      <h4>GET 10% OFF</h4>
      <p>Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.</p>
      <form class="form" method="POST" action="{% url 'subscribe' %}">
        {% csrf_token %}
        <input type="email" name="email" placeholder="Your email address">
        <button class="normal">Sign Up</button>
      </form>
    </div>
  </footer>

  <script src="https://kit.fontawesome.com/d990a4246b.js" crossorigin="anonymous"></script>
  <script src="{% static 'js/main.js' %}"></script>
    
</body>
</html>

store/templates/store/checkout.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}
Checkout
{% endblock title %}
{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}">
	<style>
		#navbar-container {
			border-bottom: 1px solid #b5b2c8;
		}
		
		#navbar-right li p,
		#navbar-bottom li a,
		#navbar-login li a,
		#navbar li a {
			color: #000;
		} 
	</style>
{% endblock css %}
{% block content %}
	<section class="section-p1">
		<form method="POST" action="{% url 'checkout' %}">
			{% csrf_token %}
			<label>First name</label><br>
        	<input type="text" name="fname" placeholder="Enter your first name" required><br>

        	<label>Last name</label><br>
        	<input type="text" name="lname" placeholder="Enter your last name" required><br>

        	<label>Email</label><br>
        	<input type="text" name="name" placeholder="Enter your email" required><br>

        	<label>Address</label><br>
        	<input type="text" name="address" placeholder="Your address" required><br>

        	<label>City</label><br>
        	<input type="text" name="city" placeholder="Your city" required><br>

        	<label>Country</label><br>
        	<input type="text" name="country" placeholder="Your country" required><br>

        	<label>Postal code</label><br>
        	<input type="text" name="postal-code" placeholder="Your postal code" required><br>

        	<input type="submit" value="Continue"/>

		</form>
		<form method="POST" action="{% 'complete_order' %}">
			
		</form>
	</section>
	<section class="section-p1">
		{% if order != None %}
			<div class="cart-container">
				<h1>Shopping Cart</h1>
				<button>CHECK OUT</button>
				<div class="grid-header">
					<h2>QUANTITY</h2>
					<h2>TOTAL</h2>
				</div>
				{% for item in order.orderitem_set.all %}
					<img src="{{ item.product.imageURL }}">
					<h5>{{ item.product.name }}</h5>
					<h5>{{ item.quantity }}</h5>
					<h5>{{ item.get_total }}</h5>
				{% endfor %}
				<br>
			</div>
			<div class="summary-table">
				<h2>Subtotal</h2>
				<p>total price</p>
				<h3>Shipping</h3>
				<p>Free!</p>
				<button><a href="{% url 'checkout' %}">CHECK OUT</a></button>
			</div>
		{% else %}
			<h1 style="text-align:center;padding: 100px">No Items in cart</h1>
		{% endif %}
	</section>
{% endblock content %}

store/templates/store/contact_us.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}
Contact Us
{% endblock title %}
{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}">
	<style>
		#navbar-container {
			border-bottom: 1px solid #b5b2c8;
		}
		
		#navbar-right li p,
		#navbar-bottom li a,
		#navbar-login li a,
		#navbar li a {
			color: #000;
		} 
	</style>
{% endblock css %}
{% block content %}
	<h1>Need Any Help? Send Us A Message</h1>
	<h4>We'll get back to you within one business day.</h4>
	<form method="POST" action="{% url 'contact_us' %}">
		{% csrf_token %}
		<label>Name</label><br>
		<input type="text" name="name" required><br>

		<label>Email</label><br>
		<input type="email" name="email" required><br>

		<label>Message</label><br>
		<textarea name="message" rows="5" required></textarea><br>

		<input type="submit" value="Send"/>
	</form>
{% endblock content %}

store/templates/store/home.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}
Main Page
{% endblock title %}
{% block css %}
	<!-- <style>
		#header {
/*    		background-image: url("/static/images/home-background.png");*/
    		height: 85vh;
    		width: 100%;
	    	background-size: cover;
    		background-position: top 50% right 0;
    		padding: 0px 200px;
  		}
  	</style> -->
{% endblock css %}
{% block header %}
<div id="hero">
    <h4 id="hero-subtitle">STYLISH ESSENTIALS FOR THE MODERN HOME</h4>
    <h1 id="hero-title">ELEVATE YOUR EVERYDAY</h1>
    <div id="hero-buttons">
        <button class="hero-button"><a href="{% url 'collection:category' slug='bestsellers' %}">SHOP BESTSELLERS</a></button>
        <button class="hero-button"><a href="{% url 'collection:category' slug='new-arrivals' %}">SHOP NEW ARRIVALS</a></button>
    </div>
</div>
{% endblock header %}
{% block content %}

<section id="departments" class="section-p1">
	<h2>SHOP BY DEPARTMENT</h2>
	<div id="department-container">
		<div class="department-box">
			<img src="{% static 'images/dep1.jpg' %}">
			<span><a href="{% url 'collection:category' slug='planters' %}">PLANTERS</a></span>
		</div>

		<div class="department-box">
			<img src="{% static 'images/dep2.jpg' %}">
			<span><a href="{% url 'collection:category' slug='kitchen' %}">KITCHEN</a></span>
		</div>

		<div class="department-box">
			<img src="{% static 'images/dep1.jpg' %}">
			<span><a href="{% url 'collection:category' slug='garden' %}">GARDEN</a></span>
		</div>

		<div class="department-box">
			<img src="{% static 'images/dep3.jpg' %}">
			<span><a href="{% url 'collection:category' slug='home-decor' %}">HOME DECOR</a></span>
		</div>

		<div class="department-box">
			<img src="{% static 'images/dep4.jpeg' %}">
			<span><a href="{% url 'collection:category' slug='bathroom' %}">BATHROOM</a></span>
		</div>

		<div class="department-box">
			<img src="{% static 'images/dep5.jpg' %}">
			<span><a href="{% url 'collection:category' slug='pets' %}">PETS</a></span>
		</div>

		<div class="department-box">
			<img src="{% static 'images/dep6.jpg' %}">
			<span><a href="{% url 'collection:category' slug='car' %}">CAR</a></span>
		</div>

		<div class="department-box">
			<img src="{% static 'images/dep7.jpg' %}">
			<span><a href="{% url 'collection:category' slug='other' %}">OTHER</a></span>
		</div>
	</div>
</section>

<section id="banners" class="section-p1">
	<div class="small-banner">
		<div class="small-banner-box">
			<h4>LIMITED TIME</h4>
			<h2>SUMMER SALE</h2>
			<h5>Up to 50% OFF everything</h5>
			<button><a href="#">SHOP DEALS</a></button>
		</div>
	</div>

	<div class="small-banner small-banner2">
		<div class="small-banner-box">
			<h4>EXTRA SAVING</h4>
			<h2>GET 10% OFF</h2>
			<h5>Use code Bohdan2023</h5>
			<button><a href="#">APPLY DISCOUNT</a></button>
		</div>
	</div>
</section>
{% for category_name, product_list in products_list.items %}
	<section id="product1" class="section-p1">
		<h2>{{ category_name|upper }}</h2>
		<div class="product-container">
			{% for product in product_list %}
				{% if forloop.counter <= 8 %}
					<div class="product-box">
						<a href="/{{product.slug}}"><img src="{{ product.productimage_set.first.imageURL }}"></a>
						{% if product.available %}
							<span class="onsale">Sale</span>
						{% else %}
							<span class="soldout">Sold</span>
						{% endif %}
						<h4>{{ product.name }}</h4>
						<div class="rating">
							<div class="star">
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
							</div>
							<p class="review-number">{{ product.reviews.count }}</p>  
							<p> reviews</p>
						</div>
						<div class="price-box">
							<span class="crossed-price">${{ product.crossed_out_price }}</span>
							<span class="price">${{ product.price }}</span>
							<span class="save">Save {{ product.calc_save }}%</span>
						</div>
					</div>
				{% endif  %}
			{% endfor %}
		
		</div>
		<div class="view-all">
			<button><a href="{% url 'collection:category' slug=category_name|lower %}">VIEW ALL</a></button>
		</div>
	</section>
{% endfor %}

{% endblock content %}

store/templates/store/privacy_policy.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}
Privacy Policy
{% endblock title %}
{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}">
	<style>
		#navbar-container {
			border-bottom: 1px solid #b5b2c8;
		}
		
		#navbar-right li p,
		#navbar-bottom li a,
		#navbar-login li a,
		#navbar li a {
			color: #000;
		} 
	</style>
{% endblock css %}
{% block content %}
	<section class="section-p1">
		<div class="policy-container">
			<h2>PRIVACY POLICY</h2>
			<p class="last">This Privacy Policy describes how sageandsill.com (the “Site” or “we”) collects, uses, and discloses your Personal Information when you visit or make a purchase from the Site.</p>

			<h4>Collecting Personal Information</h4>
			<p class="last">When you visit the Site, we collect certain information about your device, your interaction with the Site, and information necessary to process your purchases. We may also collect additional information if you contact us for customer support. In this Privacy Policy, we refer to any information that can uniquely identify an individual (including the information below) as “Personal Information”. See the list below for more information about what Personal Information we collect and why.</p>

		</div>
	</section>
{% endblock content %}